services:
  frontend:
    image: yuvraj96/dockerexperiment:frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: yuvraj96/dockerexperiment:backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/appdb
    depends_on:
      - db

  db:
    image: yuvraj96/dockerexperiment-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
